-- AlterTable
ALTER TABLE "salary_slip" ALTER COLUMN "salary_date" SET DATA TYPE TEXT,
ALTER COLUMN "over_time" SET DEFAULT 0.00,
ALTER COLUMN "over_time" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "paid_leave" DROP NOT NULL,
ALTER COLUMN "paid_leave" SET DEFAULT 0.00,
ALTER COLUMN "paid_leave" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "absent" SET DEFAULT 0.00,
ALTER COLUMN "absent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_deduction" DROP NOT NULL;
