-- AlterTable
ALTER TABLE "leaves" ALTER COLUMN "employee_id" SET DATA TYPE TEXT,
ALTER COLUMN "start_date_time" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "end_date_time" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "reason_for_leave" SET DATA TYPE TEXT,
ALTER COLUMN "note" SET DATA TYPE TEXT,
ALTER COLUMN "status" SET DATA TYPE TEXT;
